name: Test

on: 
  workflow_dispatch
    input:
            test_suit:
              description: 'select on test' 
              required: true 
              default: 'all'
              type: choice
              options:
                      - unit
                      - e2      
                      - all  
    jobs:
      test:
        runs-on: ubuntu-latest
        steps:
        - name: checkout code
          uses: actions/checkout@v2
        - name: Run selected test suite
          run: |
              echo "Running ${{ github.event.inputs.test_suite }} tests"         
